server:
  port: 8080
  servlet:
    context-path: /
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pns?useUnicode=true&characterEncoding=UTF-8&useJDBC49CompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: root
  tencent:
    secretId: AKIDFJ6dtsb3GCrFMCl34oIWTAajcEZdRzHI
    secretKey: lFTQ5TbSu50e17vTkjRu61e18yXprc6I
    bucket: ap-beijing
    bucketName: wyx-1303917755
    path: https://wyx-1303917755.cos.ap-beijing.myqcloud.com
    qianzui: img
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true




